name: Run Tests

on:
  push:
    branches:
      - main
  workflow_dispatch: # Correct placement for manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t ubuntu-boost env/

      - name: Run Tests
        run: |
          docker run --rm \
            --privileged \
            --env-file ${{ github.workspace }}/env/.env \
            -v ${{ github.workspace }}:/data/technicalTest:rw \
            ubuntu-boost